INSERT INTO maps(id, name) VALUES ('de_ancient', 'Ancient'),
                                  ('de_calavera', 'Calavera'),
                                  ('de_cbble', 'Cobblestone'),
                                  ('de_dust2', 'Dust 2'),
                                  ('de_inferno', 'Inferno'),
                                  ('de_mirage', 'Mirage'),
                                  ('de_nuke', 'Nuke'),
                                  ('de_overpass', 'Overpass'),
                                  ('de_pitstop', 'Pitstop'),
                                  ('de_shortdust', 'Shortdust'),
                                  ('de_shortnuke', 'Nuke'),
                                  ('de_train', 'Train'),
                                  ('de_vertigo', 'Vertigo');
