version: "3.7"

services:
  database:
    image: "postgres:alpine"
    restart: always
    ports:
    - 5432:5432
    environment:
      - POSTGRES_USER
      - POSTGRES_PASSWORD
      - POSTGRES_DB
    volumes:
      - database:/var/lib/postgresql/data
      - ./database/init:/docker-entrypoint-initdb.d

  manager:
    build:
      context: .
      dockerfile: manager/Dockerfile
    depends_on:
      - database
    environment:
      - PUBLIC_IP
      - POSTGRES_HOST = 'database'
      - POSTGRES_USER
      - POSTGRES_PASSWORD
      - POSTGRES_DB
      - PORT_MIN
      - PORT_MAX
      - GOTV_PORT_MIN
      - GOTV_PORT_MAX
    ports:
    - "$PORT_MIN-$PORT_MAX:$PORT_MIN-$PORT_MAX/tcp"
    - "$PORT_MIN-$PORT_MAX:$PORT_MIN-$PORT_MAX/udp"
    - "$GOTV_PORT_MIN-$GOTV_PORT_MAX:$GOTV_PORT_MIN-$GOTV_PORT_MAX/udp"
    volumes:
     - /var/run/docker.sock:/var/run/docker.sock

#  discord:
#    build: discord
#    depends_on:
#      - database
#    environment:
#      BOT_TOKEN: bot_token

#  web:
#    build: web
#    depends_on:
#      - database
#    environment:
#    - POSTGRES_USER
#    - POSTGRES_PASSWORD
#    - POSTGRES_DB

volumes:
  database:
